import Header from "@/components/shared/Header";
import "./globals.css";
import Footer from "@/components/shared/Footer";

export const metadata = {
  title: "Faster UI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div id="app" className="duration-300">
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
