import Header from "@/components/shared/Header";
import "./globals.css";

export const metadata = {
  title: "Faster UI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Header /> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
